# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu2204"
  config.vm.hostname = "foundryvtt"
  config.vm.define "foundryvtt"
  config.vm.network :private_network, ip: "192.168.56.48"
    
  config.vm.provider "virtualbox" do |vb|
    vb.name = "foundryvtt"
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--cpus", 2]
  end
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end
end

